services:
  - type: web
    name: blue-whale-app
    env: node
    buildCommand: bash render-deploy.sh
    startCommand: |
      if [ -f dist/index.js ]; then
        node dist/index.js
      elif [ -f dist/start.js ]; then
        node dist/start.js
      else
        echo "ERROR: No executable file found"
        exit 1
      fi
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: blue-whale-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

databases:
  - name: blue-whale-db
    plan: starter