services:
  - type: web
    name: blue-whale-app
    env: node
    buildCommand: node render-build.js || node manual-build.cjs || node deploy.js
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: blue-whale-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

databases:
  - name: blue-whale-db
    plan: starter